// This file is autogenerated by the hyperdispatch compiler
/* eslint-disable camelcase */

const { c, b4a, assert } = require('hyperdispatch/runtime')
const { version, getEncoding, setVersion } = require('./messages.js')

const defaultVersion = version

class Router {
  constructor () {
    this._handler0 = null
    this._handler1 = null
    this._handler2 = null
    this._handler3 = null
    this._handler4 = null
    this._handler5 = null
    this._handler6 = null
    this._handler7 = null
    this._handler8 = null
    this._handler9 = null
    this._handler10 = null
    this._handler11 = null
    this._handler12 = null

    this._missing = 13
  }

  add (name, handler) {
    switch (name) {
      case '@server/create-server':
        this._handler0 = handler
        break
      case '@server/update-server':
        this._handler1 = handler
        break
      case '@server/create-channel':
        this._handler2 = handler
        break
      case '@server/update-channel':
        this._handler3 = handler
        break
      case '@server/delete-channel':
        this._handler4 = handler
        break
      case '@server/send-message':
        this._handler5 = handler
        break
      case '@server/edit-message':
        this._handler6 = handler
        break
      case '@server/delete-message':
        this._handler7 = handler
        break
      case '@server/set-role':
        this._handler8 = handler
        break
      case '@server/create-user':
        this._handler9 = handler
        break
      case '@server/create-invite':
        this._handler10 = handler
        break
      case '@server/claim-invite':
        this._handler11 = handler
        break
      case '@server/revoke-invite':
        this._handler12 = handler
        break
      default:
        throw new Error('Cannot register a handler for a nonexistent route: ' + name)
    }
    this._missing--
  }

  _checkAll () {
    assert(this._handler0 !== null, 'Missing handler for "@server/create-server"')
    assert(this._handler1 !== null, 'Missing handler for "@server/update-server"')
    assert(this._handler2 !== null, 'Missing handler for "@server/create-channel"')
    assert(this._handler3 !== null, 'Missing handler for "@server/update-channel"')
    assert(this._handler4 !== null, 'Missing handler for "@server/delete-channel"')
    assert(this._handler5 !== null, 'Missing handler for "@server/send-message"')
    assert(this._handler6 !== null, 'Missing handler for "@server/edit-message"')
    assert(this._handler7 !== null, 'Missing handler for "@server/delete-message"')
    assert(this._handler8 !== null, 'Missing handler for "@server/set-role"')
    assert(this._handler9 !== null, 'Missing handler for "@server/create-user"')
    assert(this._handler10 !== null, 'Missing handler for "@server/create-invite"')
    assert(this._handler11 !== null, 'Missing handler for "@server/claim-invite"')
    assert(this._handler12 !== null, 'Missing handler for "@server/revoke-invite"')
  }

  async dispatch (encoded, context) {
    if (this._missing > 0) {
      this._checkAll()
    }

    const state = { buffer: encoded, start: 0, end: encoded.byteLength }
    const id = c.uint.decode(state)

    setVersion(defaultVersion)

    switch (id) {
      case 0:
        return this._handler0(route0.enc.decode(state), context)
      case 1:
        return this._handler1(route1.enc.decode(state), context)
      case 2:
        return this._handler2(route2.enc.decode(state), context)
      case 3:
        return this._handler3(route3.enc.decode(state), context)
      case 4:
        return this._handler4(route4.enc.decode(state), context)
      case 5:
        return this._handler5(route5.enc.decode(state), context)
      case 6:
        return this._handler6(route6.enc.decode(state), context)
      case 7:
        return this._handler7(route7.enc.decode(state), context)
      case 8:
        return this._handler8(route8.enc.decode(state), context)
      case 9:
        return this._handler9(route9.enc.decode(state), context)
      case 10:
        return this._handler10(route10.enc.decode(state), context)
      case 11:
        return this._handler11(route11.enc.decode(state), context)
      case 12:
        return this._handler12(route12.enc.decode(state), context)
      default:
        throw new Error('Handler not found for ID:' + id)
    }
  }
}

function dispatch (name, message, { version = defaultVersion } = {}) {
  const state = { buffer: null, start: 0, end: 0 }

  const o = getEncoderAndId(name)
  setVersion(version)

  c.uint.preencode(state, o.id)
  o.enc.preencode(state, message)

  state.buffer = b4a.allocUnsafe(state.end)
  c.uint.encode(state, o.id)
  o.enc.encode(state, message)

  return state.buffer
}

const route0 = {
  id: 0,
  enc: getEncoding('@server/server')
}

const route1 = {
  id: 1,
  enc: getEncoding('@server/server')
}

const route2 = {
  id: 2,
  enc: getEncoding('@server/channel')
}

const route3 = {
  id: 3,
  enc: getEncoding('@server/channel')
}

const route4 = {
  id: 4,
  enc: getEncoding('@server/channel')
}

const route5 = {
  id: 5,
  enc: getEncoding('@server/message')
}

const route6 = {
  id: 6,
  enc: getEncoding('@server/message')
}

const route7 = {
  id: 7,
  enc: getEncoding('@server/message')
}

const route8 = {
  id: 8,
  enc: getEncoding('@server/role')
}

const route9 = {
  id: 9,
  enc: getEncoding('@server/user')
}

const route10 = {
  id: 10,
  enc: getEncoding('@server/invite')
}

const route11 = {
  id: 11,
  enc: getEncoding('@server/invite')
}

const route12 = {
  id: 12,
  enc: getEncoding('@server/invite')
}

function getEncoderAndId (name) {
  switch (name) {
    case '@server/create-server':
      return route0
    case '@server/update-server':
      return route1
    case '@server/create-channel':
      return route2
    case '@server/update-channel':
      return route3
    case '@server/delete-channel':
      return route4
    case '@server/send-message':
      return route5
    case '@server/edit-message':
      return route6
    case '@server/delete-message':
      return route7
    case '@server/set-role':
      return route8
    case '@server/create-user':
      return route9
    case '@server/create-invite':
      return route10
    case '@server/claim-invite':
      return route11
    case '@server/revoke-invite':
      return route12
    default:
      throw new Error('Handler not found for name: ' + name)
  }
}

module.exports = {
  version,
  dispatch,
  Router
}
